name: notify pr approve

on:
  pull_request:
    types: [submitted]

jobs:
  Notify:
    runs-on: [ubuntu-latest]
    steps:
      - name: Send Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "SLACK PR 알림",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "PR 승인했습니다👍\n<${{ github.event.pull_request.html_url }}|PR 확인하러 가기>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
